version: "3"

services:
  web:
    build: .
    restart: always
    ports: 
      - 8055:8055
    links:
      - db
      - broker

  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=statselec
    ports:
      - 127.0.0.1:5432:5432
    # Comment this part if you don't wan't persistance data
    volumes:
      - ./container_content/psql:/var/lib/postgresql/data

  broker:
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - 1883:1883
      - 9001:9001